export const ADMIN_ROUTES = {
  root: "/admin",
  dashboard: "/admin",
  dashboardOverview: "/admin/overview",
  dashboardEngagement: "/admin/engagement",
  dashboardReviews: "/admin/reviews",
  accounts: "/admin/accounts",
  users: "/admin/accounts/users",
  activeCoaches: "/admin/accounts/active-coaches",
  coachGovernance: "/admin/coach-governance",
  coachApplications: "/admin/coach-governance/applications",
  coachPrices: "/admin/coach-governance/coach-prices",
  reports: "/admin/reports",
  openReports: "/admin/reports/open",
  closedReports: "/admin/reports/closed",
  exercises: "/admin/exercises",
  exerciseManagement: "/admin/exercises/management",
  videoModeration: "/admin/exercises/video-moderation",
  workouts: "/admin/workouts",
  workoutManagement: "/admin/workouts/management",
} as const;
